-- TODO: Add primary key to id
CREATE TABLE invpats(
  id SERIAL,
  firstname TEXT,
  lastname TEXT,
  street TEXT,
  city TEXT,
  state TEXT,
  country TEXT,
  zipcode TEXT,
  lat REAL,
  lon REAL,
  invseq INT,
  patent TEXT,
  gyear INT,
  appyearStr TEXT,
  appdateStr TEXT,
  assignee TEXT,
  asgnum     VARCHAR(16),
  class TEXT,
  invnum TEXT,
  lower TEXT,
  upper      VARCHAR(16),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
