object @invpats
attributes :id,
           :firstname,
           :lastname,
           :street,
           :city,
           :state,
           :country,
           :zipcode,
           :lat,
           :lon,
           :invseq,
           :patent,
           :gyear,
           :appyearstr,
           :appdatestr,
           :assignee,
           :asgnum,
           :patentclass,
           :coauthor,
           :invnum,
           :lower,
           :upper
           